// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtou6iAGt9nf1O5OSxYqpU1Y4y1U-Z304',
    appId: '1:817960805175:web:1dfe3a56a1cf322b3bb0b2',
    messagingSenderId: '817960805175',
    projectId: 'ludo-app-eefe1',
    authDomain: 'ludo-app-eefe1.firebaseapp.com',
    databaseURL: 'https://ludo-app-eefe1-default-rtdb.firebaseio.com',
    storageBucket: 'ludo-app-eefe1.firebasestorage.app',
    measurementId: 'G-2V3VE0Y21M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4S72UWA6IPOctwK_9EaccjQAoMqZpraA',
    appId: '1:817960805175:android:c05af82b63bdff303bb0b2',
    messagingSenderId: '817960805175',
    projectId: 'ludo-app-eefe1',
    databaseURL: 'https://ludo-app-eefe1-default-rtdb.firebaseio.com',
    storageBucket: 'ludo-app-eefe1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ6gUvuYeIbRl1Kw_vMKrU5lnPovyfIqk',
    appId: '1:817960805175:ios:64e02daa2c9150d33bb0b2',
    messagingSenderId: '817960805175',
    projectId: 'ludo-app-eefe1',
    databaseURL: 'https://ludo-app-eefe1-default-rtdb.firebaseio.com',
    storageBucket: 'ludo-app-eefe1.firebasestorage.app',
    iosBundleId: 'com.example.ludoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ6gUvuYeIbRl1Kw_vMKrU5lnPovyfIqk',
    appId: '1:817960805175:ios:64e02daa2c9150d33bb0b2',
    messagingSenderId: '817960805175',
    projectId: 'ludo-app-eefe1',
    databaseURL: 'https://ludo-app-eefe1-default-rtdb.firebaseio.com',
    storageBucket: 'ludo-app-eefe1.firebasestorage.app',
    iosBundleId: 'com.example.ludoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtou6iAGt9nf1O5OSxYqpU1Y4y1U-Z304',
    appId: '1:817960805175:web:41d5ed80969b447b3bb0b2',
    messagingSenderId: '817960805175',
    projectId: 'ludo-app-eefe1',
    authDomain: 'ludo-app-eefe1.firebaseapp.com',
    databaseURL: 'https://ludo-app-eefe1-default-rtdb.firebaseio.com',
    storageBucket: 'ludo-app-eefe1.firebasestorage.app',
    measurementId: 'G-N14PE916GC',
  );

}